services:
  container:
    build: .
    network_mode: host
    restart: unless-stopped
    environment:
      GEMINI_COOKIE_PATH: /tmp/gemini_webapi
    volumes:
      - ./:/app
      - ./gemini_cookies:/tmp/gemini_webapi
